### ISSUE TITLE
Internet connected required when the device is connected to internet

### ISSUE THREAD

**Issue by xuluna** [bitwarden/ios#896]
### Bitwarden Beta

- [ ] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Open bitwarden app
2. Input self hosted configurations
3. Input username

### Expected Result

Input password and log in successfully

### Actual Result

Pop out window saying “internet connection required”. The web UI works fine so it’s not Internet issue.

### Additional Context

https://vaultwarden.discourse.group/t/error-when-connecting-from-ios-app/3954

### Build Version

2024.8.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by xuluna** [comment]
I just took a screenshot of the error message. Let me know anything else I can provide. 
![Screenshot 2024-09-05 at 1 40 51 PM](https://github.com/user-attachments/assets/620c649b-b7e6-4c08-957b-2d9b25c6024a)

**Comment by xuluna** [comment]
Here’s another screenshot to show that I can connect to the server with browser on the same device. 
![Uploading Vaultwarden Web.png…]()

**Comment by xuluna** [comment]
Here’s another screenshot to show that I can connect to the server with browser on the same device.
![Vaultwarden Web](https://github.com/user-attachments/assets/1b4b4b49-f54b-480f-b882-b91999a474a7)

**Comment by stonith404** [comment]
I'm having the same issue. The bug only occurs if you select a self-hosted instance.

With 2024.8.0 I don't get the error, so 2024.8.1 must probably have broken something.

**Comment by natonic77** [comment]
I'm seeing this issue as well, and I'm only seeing it on iPads (mine is running iOS 17 with 2024.8.1). I also run the iOS client on iPhone (2024.8.1 also) and do not see this issue on the same network with the same self-hosted server. I never ran 2024.8.0, but I have a different iPad running 2024.7.1 and don't see the issue there. As noted by others, I can access the web vault on the same device without issue.

**Comment by mrbill430** [comment]
I'm having the same issue on an iPhone 14, IOS 18.  I host the official docker instance on my local network.  When connected to the local network I have the issue.  When I'm mobile and connect back to my home network via wireguard everything works fine.  The web interface and windows client work fine when connected to the local network.

It only happens when connecting to self hosted instance when on the same local network on my iPhone.

**Comment by natonic77** [comment]
Just upgraded my iPad to iOS 18.0.1 (from iOS 17), also updated to Bitwarden 2024.9.2. Problem seems to have been resolved. Wondering if it might have been this fix: https://github.com/bitwarden/ios/pull/878.

**Comment by nitingupta131** [comment]
I am still seeing the same issue is there any update on this?

**Comment by sololegends** [comment]
Same issue only a problem on the iPad with self-hosted up to date server. Can access from a web browser no.problem. 
bitwarden 2025.6.0 
iOS 18.5

**Comment by sololegends** [comment]
Actually may have found the solution. 

You have to go to Settings -> Privacy and Security -> Local Network -> tick it on for bitwarden 

This apparently means the app may access things inside your local network, not scan for devices as the permission implies. 

Hope this helps someone else too

**Comment by yolocalhost** [comment]
I have tried Local networks enabled, but same result, "Internet connection required."

**Comment by nitrag** [comment]
I dug into my app logs. 

I was seeing: `Error: Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost."`

The server logs said it was returning a response of HTTP 200. 

The issue was with my Nginx proxy in front of my server. I added the following to my nginx config:

```
proxy_buffer_size   32k;
proxy_buffers       16 32k;
proxy_busy_buffers_size 64k;
```

and since I was seeing this error: `"/var/lib/nginx/proxy/1/00/0000000001" failed (13: Permission denied) while reading upstream,` I also reset permissions for good measure

```bash
sudo systemctl stop nginx
sudo rm -rf /var/lib/nginx/proxy/*
sudo chmod -R u=rwX,go= /var/lib/nginx
sudo systemctl start nginx
```
